### ISSUE TITLE
Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.

### ISSUE THREAD

**Issue by umutcoskun** [natintosh/intl_phone_number_input#335] opened 2022-07-24 16:27 UTC
**Describe the bug**
```
intl_phone_number_input-0.7.0+2/lib/src/widgets/input_widget.dart:321:20: Warning: Operand of null-aware operation '!' has type 'WidgetsBinding' which excludes null.
 - 'WidgetsBinding' is from 'package:flutter/src/widgets/binding.dart' ('../../Public/flutter/packages/flutter/lib/src/widgets/binding.dart').
    WidgetsBinding.instance!.addPostFrameCallback((timeStamp) {
                   ^
```

**Package version**
0.7.0+2

**Flutter version**
3.0.5

**To Reproduce**
Just include and use the library.

**Expected behavior**
No errors throwed from the library.

**Targeted platforms:**
 - Android
 - iOS

**Comment by SimonH-Zuma** [comment] 2022-07-26 09:39
Duplicate of #323

**Comment by bynalab** [comment] 2022-08-25 08:48
Closing this issue now has #323 has been addressed and merged.

**Closed by bynalab** 2022-08-25 08:48 UTC
