### ISSUE TITLE
Search by Country name or dial code bug

### ISSUE THREAD

**Issue by lordvidex** [natintosh/intl_phone_number_input#197] opened 2021-03-30 14:25 UTC
**Describe the bug**
When using selectorConfig of PhoneInputSelectorType.BOTTOM_SHEET, the bottom sheet displays badly when user tries to search on Android

**Package version**
intl_phone_number_input: 0.6.0

**Flutter version**
Flutter 2.0.0

**Expected behavior**
BottomSheet should open taking the available space without breaking UI

**Screenshots**
<img width="323" alt="Screen Shot 2021-03-30 at 5 22 00 PM" src="https://user-images.githubusercontent.com/49334512/113004788-88addd00-917c-11eb-8d8e-65c52da7bb15.png">

** Targeted platforms :**
 - Android

**Comment by natintosh** [comment] 2021-03-30 14:36
Duplicate of #187.

**Closed by natintosh** 2021-03-30 14:36 UTC

**Comment by lordvidex** [comment] 2021-03-30 14:42
#187 was an overflow error. I received none but the listview containing the countries isn't showing properly as shown in the screenshot above

**Comment by natintosh** [comment] 2021-03-30 14:56
Hi @lordvidex, The issue has been fixed. The overflow error was a subset of the bug itself. I will be releasing an update very soon. Thanks for opening this issue

<img width="332" src="https://user-images.githubusercontent.com/27495055/113009509-ebe54280-916f-11eb-95fc-d074c2946690.png" />
