### ISSUE TITLE
Formating can remove digits from number

### ISSUE THREAD

**Issue by LastExileUA** [natintosh/intl_phone_number_input#56] opened 2020-05-25 09:05 UTC
If you set `autoFormat: true` or set `PhoneNumber(isoCode: 'BR', '5167634469')`, it remove lead "5" digit.
[gif to demonstrate](https://github.com/LastExileUA/intl_phone_number_input/blob/develop/bug.gif?raw=true)

It's happen because `value.replaceAll(RegExp('^([\\+?${this.dialCode}\\s?]+)'), '')`, it can eat next digits after _dialCode_, works not only with BR.
I replaced it with `value.replaceFirst(RegExp('^([\\+]?${number.dialCode}[\\s]?)', '')`, and it works fine. Replace has been made in `phone_number.dart` and `as_you_type_formatter.dart`

I have done it in my [fork](https://github.com/LastExileUA/intl_phone_number_input)

**Comment by vanshg395** [comment] 2020-05-26 09:31
I am facing same issue, this was not getting fixed so I made my own phone field. You can use it from here until this is fixed.

https://pub.dev/packages/intl_phone_field

**Comment by natintosh** [comment] 2020-05-27 09:04
Hi @LastExileUA  thanks for raising this issue, it is quite similar to #40 I was unable to find out the cause of this but now I know and its all thanks to you. 👍👍👍

**Comment by natintosh** [comment] 2020-05-28 16:57
Hi, @LastExileUA  I just pushed a fix, I need to resolve some issues before I publishing. Thank again.

**Closed by natintosh** 2020-05-28 16:57 UTC
